### PR TITLE
Allow negative index with direct channel write

### PR DESCRIPTION
**Pull request by ArthurDent62**

### CODE REVIEW

**Comment by ArthurDent62** [comment]
In response to issue #11

**Comment by ArthurDent62** [comment]
@brennen Can you give an approximate date when you will be able to review? My impression is that the #10 depends on this PR being handled first. Thank you.

**Comment by brennen** [comment]
Hey @ArthurDent62 - apologies; I've been a bit head down elsewhere, but I'll give this one a test yet today.

**Comment by ArthurDent62** [comment]
@brennen no prob at all. I don't want to urge at all, really. Just to know when it would make sense to check back.

**Pull request merged**
