### PR TITLE
use existing spi baudrate instead of hardcoded

### LINKED ISSUE #22: SPI baudrate hardcoded, should use existing frequency from SPI object
This is the same issue as https://github.com/adafruit/Adafruit_CircuitPython_TLC59711/issues/8. 

Problematic code is here: https://github.com/adafruit/Adafruit_CircuitPython_TLC5947/blob/60d36538ccb9591e5aeaa8c733c184119bb61448/adafruit_tlc5947.py#L161

@FoamyGuy Are you up for fixing this like you did the other TLC lib?

### PR DESCRIPTION
**Pull request by FoamyGuy**
resolves #22. I don't have hardware to test it, but wouldn't anticipate problems since it's mostly the same as: [#14](https://github.com/adafruit/Adafruit_CircuitPython_TLC59711/pull/14) from the TLC59711 library.

### CODE REVIEW

**Comment by evaherrada** [comment]
@FoamyGuy Do you think you could update this to match what @tannewt said in #22? I think that would probably need some testing though

**Comment by FoamyGuy** [comment]
@dherrada thanks for the reminder. I definitely missed that message on the issue. 

Latest commit removes the configure. I don't have hardware to test with and it looks like they are showing out of stock at the moment. 

I can go back and attempt to make a similar change on the TLC59711 and test it with that device though.

**Comment by evaherrada** [comment]
@FoamyGuy Were you ever able to test this?

**Comment by FoamyGuy** [comment]
@dherrada I did test it on a modified branch with the TLC59711 and didn't see any trouble. Though the modified code for it seems to have gotten lost in the shuffle between my old and new laptops.

**Comment by evaherrada** [comment]
Awesome. Thanks!

**Pull request merged**
